### PR TITLE
decimal format for numbers > 1e21

### LINKED ISSUE #24: The decimal format (d) isn’t observed if x ≥ 1e21.
For example:

``` js
var f = d3.format(",d");
f(1e20); // "100,000,000,000,000,000,000"
f(1e21); // "1e+21"
```

Because:

``` js
(1e20).toString(10); // "100000000000000000000"
(1e21).toString(10); // "1e+21"
```

Related #21.

### PR DESCRIPTION
**Pull request by Fil**
fixes #24

### CODE REVIEW

**Comment by enjalot** [comment]
looks good, I pulled apart the line to double-check my understanding https://observablehq.com/d/4353074098da94bc

**Comment by mbostock** [comment]
Thanks for this PR.

I don’t think this is quite the behavior we want; I think we should attempt to match the behavior of *number*.toPrecision rather than appending zeroes for whatever is truncated by *number*.toString. For example:

```
> (123456789012345678901234567890).toString(10)
'1.2345678901234568e+29'
> (123456789012345678901234567890).toPrecision(30)
'123456789012345677877719597056'
```

This PR would return `123456789012345680000000000000` for the format `d`, but I think `123456789012345677877719597056` is a better answer since it is closer to the true binary floating value.

That said, I’m not sure off the top of my head how to most easily achieve this result. We could perhaps use *number*.toPrecision, but I’m not sure what precision we would pass, and that is still limited to 100 digits in modern browsers. We could use `BigInt(…).toString()` but that’s also got downsides. I think we should do a little more digging before landing this PR.

**Comment by Fil** [comment]
Ha, I didn't know about Number.toPrecision.

Indeed it seems better to use (123456789012345678901234567890).toPrecision(100).replace(/\.0+$/, ""), if supported—but ES6 https://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.toprecision seems to say that the maximum precision can be 21, or more, or less… and no way to read the value 😰

(Bigint works quite well but support is not very wide atm.)

**Comment by mbostock** [comment]
Superseded by #104.

**Pull request closed without merging**
